apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-orders-deployment
spec:
  selector:
    matchLabels:
      app: ctse-orders
  template:
    metadata:
      labels:
        app: ctse-orders
    spec:
      containers:
      - name: ctse-orders
        image: 0712741286/ctse_orders:1.0.2
        ports:
        - containerPort: 3004