apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-cart-deployment
spec:
  selector:
    matchLabels:
      app: ctse-cart
  template:
    metadata:
      labels:
        app: ctse-cart
    spec:
      containers:
      - name: ctse-cart
        image: rusira123docker/ctse_cart:1.0.4
        ports:
        - containerPort: 3002
