kind: Service
apiVersion: apps/v1
metadata:
  name: ctse-cart-service
spec:
  selector:
    matchLabels:
      app: ctse-cart
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: LoadBalancer