apiVersion: v1
kind: Service
metadata:
    name: "kubectseass3-baa9"
    labels:
        app: "kubectseass3-baa9"
spec:
    type: LoadBalancer
    ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
    selector:
        app: "kubectseass3-baa9"