apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-items-deployment
spec:
  selector:
    matchLabels:
      app: ctse-items
  template:
    metadata:
      labels:
        app: ctse-items
    spec:
      containers:
      - name: ctse-items
        image: thushaltk/ctse_items:1.0.4
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: ctse-items-service
spec:
  selector:
      app: ctseItemsService
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: LoadBalancer