kind: Service
apiVersion: apps/v1
metadata:
  name: ctse-items-service
spec:
  selector:
    matchLabels:
      app: ctse-items
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: LoadBalancer