apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-users-deployment
spec:
  selector:
    matchLabels:
      app: ctse-users
  template:
    metadata:
      labels:
        app: ctse-users
    spec:
      containers:
      - name: ctse-users
        image: kishdeemu/ctse_users:1.0.1
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: ctse-users-service
spec:
  selector:
      app: ctseUsersService
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
  type: LoadBalancer