apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-users-deployment
spec:
  selector:
    matchLabels:
      app: ctse-users
  template:
    metadata:
      labels:
        app: ctse-users
    spec:
      containers:
      - name: ctse-users
        image: kishdeemu/ctse_users:1.0.3
        ports:
        - containerPort: 3005
