kind: Service
apiVersion: apps/v1
metadata:
  name: ctse-users-service
spec:
  selector:
    matchLabels:
      app: ctse-users
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
  type: LoadBalancer