# This is a basic workflow to help you get started with Actions

name: AKS Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
        
      - name: Building docker image for "ItemsService"
        run: cd services/Items; docker build --platform amd64 -t thushaltk/ctse_items:'${{github.sha}}' .
        
      - name: Dockerhub authentication
        run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'
        
      - name: Pushing docker image to dockerhub
        run: docker push thushaltk/ctse_items:'${{github.sha}}' 
        
      - name: Azure login
        run: az login -u '${{secrets.AZURE_USERNAME}}' -p '${{secrets.AZURE_PASSWORD}}'
        
      - name: Setting azure subscription
        run: az account set --subscription 14168ade-3357-4b6b-8e3a-b97bde79c54f

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v2.1
        with:
          # Resource Group Name
          resource-group: ctse_assignment03
          # AKS Cluster Name
          cluster-name: kube_ctse_ass3
          
          
      - name: Create secret in Kubernetes cluster
        uses: Azure/k8s-create-secret@v2.1
        with:
          container-registry-url: https://index.docker.io/v1/
          container-registry-username: '${{secrets.DOCKER_USERNAME}}'
          container-registry-password: '${{secrets.DOCKER_PASSWORD}}'
          secret-type: docker-registry
          secret-name:  docker-image-pull-secret
          
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.1
        with:
          manifests: services/Items/deployment.yaml
          images: thushaltk/ctse_items:'${{github.sha}}'
          imagepullsecrets: docker-image-pull-secret
          action: deploy


